# Generated by Django 4.1.3 on 2022-12-04 01:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tags", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Tag",
            new_name="Tags",
        ),
    ]
