name: Tests, Linting, Formatting, and Type Checking

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  DEBUG: ${{ vars.DEBUG }}
  DJANGO_ALLOWED_HOSTS: ${{ vars.DJANGO_ALLOWED_HOSTS }}
  TEST_DB_NAME: ${{ vars.TEST_DB_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: matheuscas/my-personal-finance-service/.github/workflows/dependencies.yml@main

      - name: Run tests
        run: |
          poetry run pytest

      - name: Check linting
        run: |
          poetry run ruff check .

      - name: Check formmatting
        run: |
          poetry run black .

      - name: Type checking
        run: poetry run mypy .
